"""empty message

Revision ID: 074f6bcba54c
Revises: 
Create Date: 2020-06-09 12:11:45.698668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '074f6bcba54c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('rolename', sa.String(length=60), nullable=False),
    sa.Column('user_id', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['trivia_user.id'], ),
    sa.PrimaryKeyConstraint('rolename', 'user_id')
    )
    op.drop_column('trivia_user', 'is_admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trivia_user', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_table('role')
    # ### end Alembic commands ###
