"""empty message

Revision ID: 5e01876b13f2
Revises: f21b83b954bc
Create Date: 2020-06-10 17:54:08.716002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e01876b13f2'
down_revision = 'f21b83b954bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('id', sa.Integer(), nullable=True))
    op.alter_column('role', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'role', ['rolename'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role', type_='unique')
    op.alter_column('role', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('role', 'id')
    # ### end Alembic commands ###
